label sleep01:
    mc "It's not our problem."
    a "...?"
    a "Is it ok??"
    a "To let them drown."
    b "I'm telling you.."
    b "It's got to be staged."
    b "What dumbass would actually do this."
    b "On accident."
    d "Are they planning to sleep forever?"
    d "That's boring."
    c "Wait don't leave me One Piece."
    d "I have to.."
    d "I have to become the pirate king."
    c "Take me with you then."
    c "I'll join your crew."
    e "STOP ROLEPLAYING"
    g "Seriously?"
    d "Let's get out of here 123"
    c "I'll go anywhere you go."
    b "Are they gone yet?"
    e "..."
    g "You know what."
    g "I'll go too."
    g "I'm getting bored."
    f "If this bozo won't wake up.."
    f "I'll go too."
    e "..."
    e "Yeah."
    e "Me too."
    a "Guys???"
    a "But but they're going to drown?"
    b "Eh."
    b "Taking too slow."
    b "I'm out."
    a "..."
    a "Am I the only one left?"
    menu: 
        "No":
            jump no02
        "Leave the stream":
            return
