label nowanna04:
    play music "audio/creepy.wav" loop
    mc "Eh I don't wanna."
    a "What do you mean.."
    a "You don't wanna."
    mc "I just don't feel like it."
    a "..."
    a "They're going to drown."
    mc "Eh."
    mc "I know."
    a "So you DO know."
    a "You DON'T think it's staged?"
    mc "No I think it's real."
    a "And you just won't?"
    mc "Yup."
    mc "Let them drown."
    mc "Shouldn't have done a 24 hour challenge."
    mc "In that house."
    a "That house...do you know this house?"
    mc "Maybe maybe not."
    a "What is your problem?"
    mc "What is yours?"
    mc "You want to save them that badly?"
    mc "Then do it yourself."
    mc "Don't tell me what to do."
    a "...I tried."
    mc "Tried running your mouth."
    mc "You're a bystander."
    mc "Just like everyone else."
    mc "You just act like you care."
    a "So what am I supposed to do?"
    mc "Nothing."
    mc "You can't do anything."
    "..."
    scene bg flood5
    a "They're drowning."
    mc "If you don't want to see."
    mc "Leave the stream."
    a "Why are you staying?"
    a "WHAT'S WRONG WITH YOU?"
    mc "The same reason you are still here."
    
    a "..."
    mc "You treat this as a show."
    mc "Screaming at the streamer.."
    mc "As if they're a character."
    mc "You want to see how this ends."
    mc "I do too."
    mc "But you refuse to admit it."
    a "Shut up."
    scene bg flood3
    a "The water..it's rising."
    mc "It is."
    mc "I can see that."
    mc "And it will keep rising."
    mc "Will you do anything about it?"
    a "You just said I can't."
    mc "Yeah you don't care enough."
    mc "If you did you would have found a way."
    a "Shut up already."
    scene bg flood4
    mc "I think it's time."
    mc "The water reached the ceiling."
    mc "How long will you be able to breath?"
    mc "AwesomeStreamer.."
    a "Do you know them??"
    a "You act like you know them?"
    mc "Why would I tell you?"
    mc "You're just a stranger on the internet."
    a "..."
    a "..They drowned didn't they."
    mc "They have."
    a "We watched it happen."
    mc "We did."
    a "What am I supposed to do..."
    mc "Nothing. Go on with your life."
    mc "You didn't know them."
    mc "It was a stream you happened to watch."
    a "How will I live with myself?"
    mc "Oh come on."
    mc "We both know you will forget this."
    mc "Give it a day or two."
    a "You disgust me."
    mc "Thanks but I think you're more gross."
    mc "Because you WILL forget."
    mc "You say woe is me."
    mc "That you're a monster."
    mc "That you'll never be able to attone."
    mc "But you will continue on with your days."
    mc "Laugh with your friends."
    mc "Go on vacations."
    mc "And today will just be like a show."
    mc "So how about you leave the stream now."
    mc "Get a headstart."
    a "And you?"
    mc "I'll leave too."
    mc "I'm done here."
    a "You got...what you wanted?"
    a "What did you want?"
    a "Why did you even log in today?"
    mc "I don't wanna tell you."
    scene bg poweroff
    mc "You're just a stranger on the internet."

    return

