label swim02:
    mc "I vote on swimming."
    mc "Love swimming."
    mc "What's the worst that can happen?"
    
    show bubble eight
    a "...In a pool."
    a "On the beach..."
    b "In the flood!"
    a "NO."
    c "Eh think about the content."
    e "Lol swimming"
    d "I can't swim."
    e "Didn't ask."
    d ":("
    scene bg flood2
    f "Oh no..."
    f "They're dipping their feet in."
    show bubble nine
    a "."
    b ":D"
    a ">:("
    g "Haha this fella's pretty stupid."
    show bubble ten
    c "I don't."
    b "Hell no."
    a "Wow."
    a "Suddenly against this?"
    b "I'm not stupid enough."
    b "But streamer can go ahead."
    b "It's funny."
    e "It's good content."
    e "If they don't die."
    a "DON'T SAY THAT."
    f "Are we accomplices?"
    f "If anything happens."
    c "Big word."
    d "Accomplice."
    show bubble eleven
    e "Are you two stupid?"
    
    a "?"
    g "?"
    h "?"
    c "!"
    scene bg flood5
    show bubble twelve
    g "They call that a flood!"
    g "Just a fun fact!"
    a "Not."
    a "Fun."
    b "Hell yeah."
    j "Do not say that word."
    b "Yeah?"
    j "The other one?"
    b "Hell?"
    j "Yeah..."
    b "Hell yeah."
    b "Wait I just read your name."
    b "Don't do it.."
    j "Mods..."
    b "I apologize."
    b "I won't do it again."
    j "Good."
    a "Can you shut the fuck up?"
    j "Don't say that word."
    a "THERE'S A FLOOD."
    show bubble thirteen
    a "Can your mods get help???"
    show bubble fourteen
    c "Heh yeah."
    
    c "THAT'S SO SMART."
    d "OH MY GOD."
    d "BOUNCY!"
    show bubble fifteen
    e "It's..buoyancy."
    
    g "What are we looking at?"
    a "What."
    a "What is it."
    play music "audio/creepy.wav" loop
    scene bg flood3
    show bubble sixteen
    a "What could it possibly b"
    
    a "Wow."
    a "JUST WOW."
    b "Why are you so pressed?"
    a "Why aren't YOU?"
    a "They're going to die!"
    show bubble seventeen
    b "Nah they aren't."
    h "Wow."
    h "Is it just me."
    h "Or is the ceiling closer."
    e "Bro."
    e "It's been getting closer."
    e "Are you high?"
    h "ME?"
    h "WHAT?"
    h "WHY I NEVER."
    show bubble eighteen
    e "..."
    
    d "AHHH."
    d "Sorry the scream scared me."
    show bubble nineteen
    a "I can't watch."
    
    i "Say that again..."
    b "Hah it's been overflowing."
    k "Yep."
    k "We call that a flood."
    g "Who is we?"
    k "The flood experts."
    a "GOOD."
    a "AN EXPERT."
    a "What can we do?"
    a "How did this flood start?"
    k "Woah."
    k "I don't know all that."
    a "..."
    a "What do you know?"
    k "That a flood is pretty scary."
    a "."
    show bubble twenty
    a "How to leave chat?"
    
    i "S s s say that again?"
    c "HAHA you're so cooked."
    d "Sorry little bro."
    a "PLEASE JUST ESCAPE."
    b "Here I thought you left."
    a "I would never."
    show bubble twentyone
    b "Shame."
    
    d "Weak."
    a "I'm scared too..."
    a "Wdym WEAK?"
    d "Me personally."
    d "I wouldn't be scared."
    a "The ceiling is right there."
    c "Nah."
    c "My homie one piece would live."
    d "I'm built diff."
    c "Yeah they saved my cat from drowning."
    e "I thought they couldn't swim."
    c "Oops."
    a "I. Do. Not. Care."
    d ":("
    c ":("
    g "Did anyone try calling the police?"
    e "What happened to that mod guy?"
    b "Fuck."
    j "Do not."
    b "There."
    g "Mod guy."
    g "Can you figure out this guy's location?"
    j "..."
    j "Uh."
    show bubble twentytwo
    j "I'll try?"
    
    b "Nah."
    b "That's boring."
    a "I will strangle you."
    j "I can't find their location."
    a "."
    g "."
    h "Woah is that a flood."
    e "Bro."
    l "Oh joys!"
    l "My baby is taking a swim."
    a "Wait."
    a "You're...their mother?"
    l "Of course!"
    l "Is my sweet pumpkin behaving?"
    show bubble twentythree
    b "SWEET PUMPKIN?"
    d "LMAO"
    g "Leave them alone."
    g "That's their mom."
    c "CRINGE!"
    a "Jerks."
    l "It's me sugarplum!"
    show bubble twentyfour
    l "I wanted to see you at work!"
    l "As a streamer."
    g "That's so sweet."
    show bubble twentyfive
    l "Anything for my baby!"
    
    a "You've got bigger problems."
    b "This IS embarrassing."
    a "KYS"
    b "Woah woah woah."
    b "What happened to caring about life?"
    c "LOL just not yours."
    a "Exactly."
    a "Shut up."
    show bubble twentysix
    a "We need to get AwesomeStreamer help."
    
    l "Flood."
    l "How dare this flood hurt my baby."
    b "L"
    l "Rage...Bait...Your...Mom?"
    l "That's a nice name."
    l "But I will find you."
    l "And I will kill you."
    e "OH????"
    c "Huh."
    g "Damn."
    b "My life's purpose..."
    b "Has it been completed."
    a "ENOUGH."
    a "Awesome's mom!"
    a "Do you have their address???"
    l "Oh!"
    l "Let me go check!"
    e "What was that..."
    e "She was so scary for a moment."
    l "Oh here!"
    l "I'll let the authorities know."
    l "But it is stormy..."
    l "Oh I hope they get to my baby."
    a "Don't worry miss."
    a "They will!"
    d "They will?"
    l "They... they..."
    a "What is it m'am??"
    l "They said they will try.."
    l "But...that the storm outside.."
    show bubble twentyseven
    l "Oh no... my baby."
    
    a "I'm going to cry too now..."
    g ":("
    c "Oh...no that old lady is crying."
    c "I feel bad.."
    d "Luffy would never approve."
    b "..."
    e "The water..."
    e "It's rising."
    g "The ceiling.."
    show bubble twentyeight
    g "It's right there."
    
    l "DON'T APOLOGIZE SWEETIE."
    l "I LOVE YOU TOO."
    l "Help is on the way.."
    l "Don't worry help is on the way..."
    menu:
        "Not like this":
            jump save04
        "None of your business":
            jump nothing05
    


